# Generated by Django 4.2.16 on 2024-11-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0003_design_table_notification_table_offer_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_table',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order_table',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order_table',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cart_table',
            name='PRODUCT_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.product_table'),
        ),
        migrations.AddField(
            model_name='design_table',
            name='Design_image',
            field=models.FileField(blank=True, null=True, upload_to='tailordesign/'),
        ),
        migrations.AddField(
            model_name='design_table',
            name='TAILOR_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.tailor_table'),
        ),
        migrations.AddField(
            model_name='notification_table',
            name='ORDER_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.order_table'),
        ),
        migrations.AddField(
            model_name='offer_table',
            name='PRODUCT_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.product_table'),
        ),
        migrations.AddField(
            model_name='order_table',
            name='Date_Time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order_table',
            name='Order_Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_table',
            name='PRODUCT_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.product_table'),
        ),
        migrations.AddField(
            model_name='payment_table',
            name='CART_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.cart_table'),
        ),
        migrations.AddField(
            model_name='request_table',
            name='Design',
            field=models.FileField(blank=True, null=True, upload_to='design/'),
        ),
        migrations.AddField(
            model_name='request_table',
            name='TAILOR_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.tailor_table'),
        ),
        migrations.AddField(
            model_name='request_table',
            name='USER_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.usertable_model'),
        ),
        migrations.AlterField(
            model_name='category_table',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='category_table',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaints_reply_table',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaints_reply_table',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification_table',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer_table',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer_table',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='review_table',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='review_table',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='notification_table',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
