# Generated by Django 4.2.16 on 2024-11-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0004_remove_notification_table_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller_table',
            old_name='Seller_name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='delivery_agent_table',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='delivery_agent_table',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='shoptable_model',
            name='Shop_address',
        ),
        migrations.RemoveField(
            model_name='shoptable_model',
            name='Shop_name',
        ),
        migrations.AddField(
            model_name='seller_table',
            name='Phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoptable_model',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoptable_model',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
