# Generated by Django 4.2.16 on 2024-12-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0005_rename_seller_name_seller_table_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_table',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
