# Generated by Django 4.2.16 on 2024-12-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0006_review_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_table',
            name='Name',
        ),
    ]
