# Generated by Django 4.2.16 on 2024-12-27 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0010_alter_product_table_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='SELLER_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.seller_table'),
        ),
    ]
