# Generated by Django 4.2.16 on 2024-12-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0012_alter_order_table_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_table',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
