# Generated by Django 4.2.16 on 2024-12-28 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0013_order_table_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Status', models.CharField(blank=True, max_length=100, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.order_table')),
                ('deliveryboy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.delivery_agent_table')),
            ],
        ),
    ]
