# Generated by Django 4.2.16 on 2024-12-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0014_assign_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_table',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
