# Generated by Django 4.2.16 on 2024-12-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0015_offer_table_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productrate_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('Review', models.CharField(blank=True, max_length=200, null=True)),
                ('Ratings', models.IntegerField(blank=True, null=True)),
                ('PRODUCT_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.product_table')),
                ('USER_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.usertable_model')),
            ],
        ),
    ]
