# Generated by Django 4.2.16 on 2024-12-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0016_productrate_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrate_table',
            name='Complaint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productrate_table',
            name='Reply',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
