# Generated by Django 4.2.16 on 2025-01-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0018_remove_complaints_reply_table_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design_table',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
