# Generated by Django 4.2.16 on 2025-01-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0020_request_table_quantity_request_table_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_table',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
