# Generated by Django 4.2.16 on 2025-01-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0022_complaints_reply_table_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='CATEGORY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.category_table'),
        ),
    ]
