# Generated by Django 4.2.16 on 2025-01-19 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0023_product_table_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_table',
            name='ORDER_ID',
        ),
        migrations.AddField(
            model_name='notification_table',
            name='ASSIGN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.assign_table'),
        ),
    ]
