# Generated by Django 4.2.16 on 2025-01-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0024_remove_notification_table_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign_table',
            old_name='deliveryboy',
            new_name='delivery_agent',
        ),
    ]
