# Generated by Django 4.2.16 on 2025-01-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0025_rename_deliveryboy_assign_table_delivery_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification_table',
            old_name='Order_name',
            new_name='status',
        ),
    ]
