# Generated by Django 4.2.16 on 2025-01-24 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0027_notification_table_orderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.CharField(blank=True, max_length=100, null=True)),
                ('Rating', models.IntegerField(blank=True, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('DeliveryAgency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.delivery_agent_table')),
            ],
        ),
    ]
