# Generated by Django 4.2.16 on 2025-01-24 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0028_reviewdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdelivery',
            name='USER_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.usertable_model'),
        ),
    ]
