# Generated by Django 5.1.2 on 2025-02-14 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedKartApp', '0029_reviewdelivery_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalamount', models.FloatField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.usertable_model')),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.product_table')),
            ],
        ),
        migrations.AlterField(
            model_name='assign_table',
            name='Order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.orderitem'),
        ),
        migrations.AlterField(
            model_name='notification_table',
            name='orderdata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedKartApp.orderitem'),
        ),
        migrations.DeleteModel(
            name='Order_Table',
        ),
    ]
